### ISSUE TITLE
@View decorator has been removed for now and is no longer optional

### ISSUE THREAD

**Issue by nbellocam** [jongalloway/aspnetcore-ng2-master-details#12]
This decorator is used in the order-app component. It should be removed and the options should be moved to the Component decorator.

https://github.com/jongalloway/aspnetcore-ng2-master-details/blob/master/src/OrderApp/wwwroot/js/order-app.component.ts#L15

**Comment by jongalloway** [comment]
Reference: https://github.com/angular/angular/pull/7495
